config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/new'
  get 'users/create'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout_custom', to: 'sessions#logout'
  root 'welcome#index'

  get '/about', to: 'users#about'
  get '/payment_info', to: 'users#payment_info'
  post '/make_payment', to: 'transactions#make_payment'
  get '/transactions', to: 'users#transactions'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user


  def self.create_new_transaction(logged_in_user, user_to_transfer, amount, description)
    transaction = Transaction.new(user: logged_in_user,
                                  destination: user_to_transfer,
                                  amount: amount,
                                  description: description,
                                  status_of_payment: 'new')
    transaction.save
    transaction
  end

  def initiate
    self.status_of_payment = 'pending'
    raise StandardError unless self.amount > 0 && self.amount < starting_point
    raise StandardError if user.id == self.destination.to_i
    user_target = User.find(self.destination)
    user.update_attribute(:bambeuro, user.bambeuro - amount)
    user_target.update_attribute(:bambeuro, user_target.bambeuro + amount)
    self.balance_after = user.bambeuro
    self.status_of_payment = 'success'
    self.timestamp = DateTime.now
    self.save
  rescue
    self.status = 'failed'
  end

  def starting_point
    self.user.bambeuro
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :transactions
  validate :unique_email
  has_secure_password
  private

  def unique_email
    existing_user = User.find_by(email: email)
    errors.add(:email, 'has already been taken') if existing_user.present?
  end

  def make_payment(email, amount)
    true unless amount > 0
    user_to_transfer = User.find_by_email(email)

  rescue
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  add_flash_types :danger, :info, :success, :warning

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  private

  def require_login
    unless logged_in?
      flash[:alert] = 'You must be logged in to access this page.'
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, info: 'Logged in successfully!'
    else
      flash.now[:danger] = 'Invalid email or password'
      render 'new'
    end
  end


  def logout
    session[:user_id] = nil
    redirect_to root_path, info: 'Logged out!'
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def make_payment
    logged_in_user = current_user
    user_to_transfer = User.find_by_email(params[:account_email])
    amount = params[:amount]
    description = params[:description]
    transaction = Transaction.create_new_transaction(logged_in_user, user_to_transfer.id, amount, description)
    transaction.initiate
    redirect_to root_path, info: 'Transaction made with success!'
  rescue
    flash.now[:danger] = 'Transaction Error'
    render 'users/payment_info'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  attr_accessor :bambeuro
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.bambeuro = 100
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, info: 'Registration successful!'
    else
      flash[:danger] = @user.errors.full_messages.join(', ')
      redirect_to signup_path
    end
  end

  def about
    @user = current_user
    render 'about'
  end

  def payment_info
    @user = current_user
    render 'payment_info'
  end

  def transactions
    @user = current_user
    @transactions = @user.transactions
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
  <a class="navbar-brand" href="#">BambBank</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= about_path %>">Details</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= payment_info_path %>">Make Payment</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= transactions_path %>">Transactions</a>
        </li>
      <% end %>
    </ul>
  </div>
  <ul class="navbar-nav">
    <% if logged_in? %>
      <li class="nav-item">
        <%= link_to 'Logout', logout_custom_path, class: 'nav-link' %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to 'Sign In', login_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign Up', signup_path, class: 'nav-link' %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <title>Vladapp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <%= javascript_include_tag "turbo" %>
</head>


  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/users/about.html.erb
<h1 class="display-5">Welcome <%= @user.name %></h1>

<p>Your email is: <%= @user.email %></p>
<p>Your remaining balance is: <%= @user.bambeuro %></p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: @user, url: signup_path) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit 'Sign up' %>
  </div>
<% end %>

app/views/users/payment_info.html.erb
<h1 class="display-5">Make a Payment</h1>
<%= form_with(url: make_payment_path) do |f| %>
  <div class="field">

  </div>

  <div class="form-group">
    <label for="name_input">Name</label>
    <%= f.text_field :account_name, class: 'form-control', placeholder: "Name"%>
    <small id="emailHelp" class="form-text text-muted">Enter the name of the person that will receive the transfer.</small>
  </div>
  <br>
  <div class="form-group">
    <label for="email_input">Email Address</label>
    <%= f.email_field :account_email, class: 'form-control', placeholder: "Email Address"%>
    <small id="emailHelp" class="form-text text-muted">Enter the email of the person that will receive the transfer.</small>
  </div>
  <br>
  <div class="form-group">
    <label for="description_input">Description</label>
    <%= f.text_field :description, class: 'form-control', placeholder: "Description"%>
    <small id="emailHelp" class="form-text text-muted">Enter the description of this transfer.</small>
  </div>
  <br>
  <div class="form-group">
    <label for="amount_input">Amount</label>
    <%= f.number_field :amount, class: 'form-control', placeholder: "0.00",  step: :any%>
    <small id="emailHelp" class="form-text text-muted">Enter the amount you want to transfer.</small>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Transfer', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/transactions.html.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col">ID</th>
    <th scope="col">Description</th>
    <th scope="col">Destination</th>
    <th scope="col">Amount</th>
    <th scope="col">Balance</th>
    <th scope="col">Date/Time</th>
    <th scope="col">Status</th>
  </tr>
  </thead>
  <tbody>
  <% @transactions.each do |transaction| %>
    <tr>
      <th scope="row"><%=transaction.id %></th>
      <td><%=transaction.description %></td>
      <td><%=User.find(transaction.destination.to_i).name if User.exists? id: transaction.destination.to_i %></td>
      <td><%=transaction.amount %></td>
      <td><%=transaction.balance_after %></td>
      <td><%=transaction.timestamp %></td>
      <td><%=transaction.status_of_payment %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
<div class="p-5 text-center">
  <% if logged_in? %>
    <h1 class="mb-3">Welcome to BampBank,  <%= current_user.name %>!</h1>
  <% else %>
    <h1 class="mb-3">Welcome to BampBank!</h1>
    <h4 class="mb-3">100 BampEuros for Free when Signing Up!</h4>
  <% end %>
</div>